In [1]:
import numpy as np
from scipy.optimize import fsolve # non-linear solver

In [2]:
"""
GAS PVT CALCULATIONS
"""

def gas_pseudoprops(temp, pressure, sg, x_h2s, x_co2):
  """
  Calculate Gas Pseudo-critical and Pseudo-reduced Pressure and Temperature
  * Pseudo-critical properties
    For range: 0.57 < sg < 1.68
    (Sutton, 1985)
  * Pseudo-reduced properties
    For range: x_h2s (mol%) < 0.738; x_co2 (mol%) < 0.544; 154 < p (psia) < 7026; 40 < temp (째F) < 300 (error 0.97%)
    (Wichert and Aziz, 1972)
  """
  
  if sg > 0.57 and sg < 1.68 and x_h2s < 0.738 and x_co2 < 0.544 and pressure > 154 and pressure < 7026 and temp > 40 and temp < 300:
    temp = temp + 459.67 # convert to Rankine

    # calculate pseudocritical properties (Sutton, valid for 0.57<sg<1.68)
    P_pc = 756.8 - (131.07 * sg) - (3.6 * sg**2)
    T_pc = 169.2 + (349.50 * sg) - (74 * sg**2) # in Rankine

    # calculate adjustment to pseudocritical properties for sour gas (Wiechert-Aziz, valid for x_co2<0.544 and x_h2s<0.738)
    e = (120 * (((x_h2s + x_co2)**0.9) - ((x_h2s + x_co2)**1.6))) + (15 * (x_h2s**0.5 - x_h2s**4))
    T_pc = T_pc - e # corrected T_pc
    P_pc = (P_pc * T_pc) / (T_pc - x_h2s * e * (1-x_h2s))

    # calculate pseudoreduced properties
    P_pr = pressure / P_pc
    T_pr = temp / T_pc
  
  else:
    P_pc, T_pc, P_pr, T_pr = np.nan, np.nan, np.nan, np.nan

  return(P_pc, T_pc, P_pr, T_pr)

def gas_zfactor(T_pr, P_pr):
  """
  Calculate Gas Compressibility Factor
  For range: 0.2 < P_pr < 30; 1 < T_pr < 3 (error 0.486%)
  (Dranchuk and Aboukassem, 1975)
  """
  # T_pr : calculated pseudoreduced temperature
  # P_pr : calculated pseudoreduced pressure   
 
  if T_pr > 1 and T_pr < 3 and P_pr > 0.2 and P_pr < 30:
    a1 = 0.3265; a2 = -1.0700; a3 = -0.5339; a4 = 0.01569; a5 = -0.05165; a6 = 0.5475
    a7 = -0.7361; a8 = 0.1844; a9 = 0.1056; a10 = 0.6134; a11 = 0.7210

    def f(y):
      rho_pr, z = y
      c1 = a1 + (a2/T_pr) + (a3/(T_pr**3))+ (a4/(T_pr**4))+ (a5/(T_pr**5))
      c2 = a6 + (a7/T_pr) + (a8/(T_pr**2))
      c3 = a9*((a7/T_pr) + (a8/(T_pr**2)))
      c4 = (a10)*(1+(a11*(rho_pr**2)))*((rho_pr**2)/(T_pr**3))*(np.exp(-a11*(rho_pr**2)))

      f1 = z + (c3*(rho_pr**5)) - (c2*(rho_pr**2)) - (c1*(rho_pr**1)) - c4 - 1
      f2 = rho_pr - ((0.27 * P_pr) / (z * T_pr))
      return[f1, f2]

    pseudo_rho, z_factor = fsolve(f, [1, 1]) # initial guess
  
  else:
    pseudo_rho, z_factor = np.nan, np.nan

  return(pseudo_rho, z_factor) # result is density, z-factor

def gas_density(temp, pressure, sg, z):
  """
  Calculate Gas Density
  For range: this is not a correlation, so valid for infinite intervals
  """  
  temp = temp + 459.67
  R = 10.732 # gas constant in (ft3*psi)/(lb-mol*R) 
  rhogas = (28.97 * sg * pressure) / (z * R * temp)
  return rhogas  

def gas_fvf(z, temp, pressure):
  """
  Calculate Gas FVF
  For range: this is not a correlation, so valid for infinite intervals
  """
  temp = temp + 459.67
  Bg = 0.0282793 * z * temp / pressure 
  return(Bg)

def gas_fvf2(unit='unit1', z=0.8, temp=186, pressure=2000):
  """
  Gas FVF calculated in other units
  unit: choice of units (unit1: RB/scf, unit2: res m3/std m3)
  for unit1, inputs temp in Rankine (Fahrenheit + 460), pressure in psia or psig
  for unit2, inputs temp in Kelvin, pressure in psia or psig
  """
  if unit == 'unit1':
    return(0.00503676 * z * temp / pressure) 
  if unit == 'unit2':
    return(0.350958 * z * temp / pressure)

def gas_mu(temp, rhogas, sg):
  """
  Calculate Gas Viscosity 
  For gas with CO2 and N2 composition
  For range: 100 < temp (째F) < 340; 0.9 < x_CO2 (mol%) < 3.2; x_N2 (mol%) < 4.8 (std 2.7-9.0%)
  (Lee et al, 1996)
  """

  if temp > 100 and temp < 340:
    temp = temp + 459.67
    Mg = 28.97 * sg
    rhogas_lee = rhogas * 0.0160185 # lbm/ft3 converted to gas density unit of Lee et al (g/cm3)
    K = ((0.00094 + 2E-06)*(temp**1.5)) / (209 + 19*Mg + temp)
    x = 3.5 + (986 / temp) + (0.01 * Mg)
    y = 2.4 - 0.2*x  
    viscogas = K * np.exp(x * (rhogas_lee**y))
  
  else:
    viscogas = np.nan
  return viscogas

def gas_compressibility(T_pr, P_pr, rho_pr, z, P_pc):
  
  """
  Calculate Gas Isothermal Compressibility for unspecified range
  (Trube, 1957; Mattar, 1975)
  """

  a1 = 0.3265; a2 = -1.0700; a3 = -0.5339; a4 = 0.01569; a5 = -0.05165; a6 = 0.5475
  a7 = -0.7361; a8 = 0.1844; a9 = 0.1056; a10 = 0.6134; a11 = 0.7210

  do = ((a1 + (a2/T_pr) + (a3/T_pr**3) +(a4/T_pr**4) + (a5/T_pr**5)) * rho_pr) + \
      (2 * ((a6 + (a7/T_pr) + (a8/T_pr**2))) * rho_pr**2) - \
      (5 * a9 * (((a7/T_pr) + (a8/T_pr**2))) * rho_pr**4) + (1 + (a11 * rho_pr**2) - (a11 * rho_pr**2)**2) \
      * ((2 * a10 * rho_pr / T_pr**3)*np.exp(-a11 * rho_pr**2))

  c_pr_analytical = (1 / P_pr) - ((0.27 / (z**2 * T_pr)) * (do / (1 + ((rho_pr / z) * do))))
  cgas_analytical = c_pr_analytical / P_pc
  return(cgas_analytical)

In [3]:
pressure = 1936 # psia
temp = 204 # Fahrenheit
sg = 1.17 # specific gravity
x_h2s = 0 # mole fraction of H2S in gas
x_co2 = 0 # mole fraction of CO2 in gas

In [4]:
# calculate gas pseudoproperties 
P_pc, T_pc, P_pr, T_pr = gas_pseudoprops(temp, pressure, sg, x_h2s, x_co2)

In [5]:
# calculate gas z-factor 
pseudo_rho, z_factor = gas_zfactor(T_pr, P_pr)

In [6]:
# calculate gas density
rhogas = gas_density(temp, pressure, sg, z_factor)

In [7]:
# calculate gas FVF
Bg = gas_fvf(z_factor, temp, pressure)

In [8]:
# calculate gas isothermal compressibility 
cgas = gas_compressibility(T_pr, P_pr, pseudo_rho, z_factor, P_pc)

In [9]:
# calculate gas viscosity 
viscogas = gas_mu(temp, rhogas, sg)

In [10]:
print('Your Input:')
print('Pressure                   : {} psia'.format(pressure))
print('Temperature                : {} 째F'.format(temp))
print('Specific Gravity           : {}'.format(sg))
print('H2S Mole Fraction          : {}'.format(x_h2s))
print('CO2 Mole Fraction          : {} \n'.format(x_co2))


print('PVT Output:')
print('z-factor                   : {}'.format(z_factor))
print('Density                    : {} lb/ft3'.format(rhogas))
print('FVF                        : {} res ft3/scf'.format(Bg))
print('Isothermal compressibility : {} microsip'.format(cgas * 1E+6))
print('Viscosity                  : {} cp'.format(viscogas))

Your Input:
Pressure                   : 1936 psia
Temperature                : 204 째F
Specific Gravity           : 1.17
H2S Mole Fraction          : 0
CO2 Mole Fraction          : 0

PVT Output:
z-factor                   : 0.7006904726987953
Density                    : 13.148634309116272 lb/ft3
FVF                        : 0.0067926885321593685 res ft3/scf
Isothermal compressibility : 494.0359376217631 microsip
Viscosity                  : 0.020657981999163168 cp

In [11]:
# Read the example of data for oil undersaturated reservoir
import pandas as pd
df = pd.read_csv('undersat_oilres_v2.csv')
df

    date     p         Np           Wp         Wi           Gp  Rs
0   1996  1950     360085      1845.00          0     23045000  64
1   1997  1834   17230861     39236.00          0   1102775000  64
2   1998  1681   38651717     97909.00          0   2473713000  64
3   1999  1560   68957151    254876.00          0   4413261000  64
4   2000  1473   95057167    297686.00      38824   6083661000  64
5   2001  1353  124251053    673783.00   12197536   7952070000  64
6   2002  1287  154528553   1011278.00   25395003   9889832000  64
7   2003  1247  191899252   2253789.00   50762076  12281556000  64
8   2004  1239  229090690   3898144.00   83580287  14661809000  64
9   2005  1231  265394171   5591112.00  115457824  16985232000  64
10  2006  1224  301951918   7856842.00  149585083  19324929000  64
11  2007  1200  338308989  10786529.00  183013606  21651781000  64
12  2008  1182  373580320  14711414.00  215140193  23909150000  64
13  2009  1138  405855680  18936798.00  242483501  25974775000  64
14  2010  1137  439503085  24703101.00  278488838  28128195000  64
15  2011  1136  456513143  28519165.41  293748836  29219820584  64

In [12]:
Z_factor = []
pressure = 1936 # psia
temp = 204 # Fahrenheit
sg = 1.17 # specific gravity
x_h2s = 0 # mole fraction of H2S in gas
x_co2 = 0 # mole fraction of CO2 in gas
for i in range(len(df)):
    P_pc, T_pc, P_pr, T_pr = gas_pseudoprops(temp, df['p'][i], sg, x_h2s, x_co2)
    pseudo_rho, z_factor = gas_zfactor(T_pr, P_pr)
    Z_factor.append(z_factor)
df['Z_factor'] = Z_factor
df

    date     p         Np           Wp         Wi           Gp  Rs  Z_factor
0   1996  1950     360085      1845.00          0     23045000  64  0.700638
1   1997  1834   17230861     39236.00          0   1102775000  64  0.702142
2   1998  1681   38651717     97909.00          0   2473713000  64  0.708127
3   1999  1560   68957151    254876.00          0   4413261000  64  0.716362
4   2000  1473   95057167    297686.00      38824   6083661000  64  0.724264
5   2001  1353  124251053    673783.00   12197536   7952070000  64  0.737850
6   2002  1287  154528553   1011278.00   25395003   9889832000  64  0.746588
7   2003  1247  191899252   2253789.00   50762076  12281556000  64  0.752293
8   2004  1239  229090690   3898144.00   83580287  14661809000  64  0.753470
9   2005  1231  265394171   5591112.00  115457824  16985232000  64  0.754658
10  2006  1224  301951918   7856842.00  149585083  19324929000  64  0.755707
11  2007  1200  338308989  10786529.00  183013606  21651781000  64  0.759368
12  2008  1182  373580320  14711414.00  215140193  23909150000  64  0.762179
13  2009  1138  405855680  18936798.00  242483501  25974775000  64  0.769273
14  2010  1137  439503085  24703101.00  278488838  28128195000  64  0.769438
15  2011  1136  456513143  28519165.41  293748836  29219820584  64  0.769603

In [13]:
def oil_Pb(Rsb, sg2, api, temp2):
  """
  Calculate Oil Bubble-Point Pressure
  For range: 20 < Rsb (scf/STB) < 2,070; 0.56 < sg < 1.18; 16 < api < 58; 70 < temp (째F) < 295 (err=0.7%)
  (Vazquez and Beggs, 1980)
  """

  if Rsb > 20 and Rsb < 2070 and sg2 > 0.56 and sg2 < 1.18 and api > 16 and api < 58 and temp2 > 70 and temp2 < 295:
    # c1, c2, c3 coefficient from Vazquez-Beggs
    if api <=30:
      c1 = 0.0362
      c2 = 1.0937
      c3 = 25.7240
    if api > 30:
      c1 = 0.0178
      c2 = 1.187
      c3 = 23.9310

    Pb = (Rsb / (c1 * sg2 * np.exp((c3 * api)/(temp2 + 459.67))))**(1 / c2) # convert temp to Rankine
  else:
    Pb = np.nan
  return Pb

def oil_fvf(P_bubble, api, Rsb, sg2, temp2, pressure2):
  """
  Calculate Oil FVF
  * Above bubble-point pressure
    For range: unspecified
    (Vazquez and Beggs, 1980)
  * At and bubble-point pressure
    For range: unspecified
    (Levitan and Murtha, 1999)
  """


  # FVF of oil at bubblepoint pressure using Levitan-Murtha
  so = 141.5 / (api + 131.5)
  Bo_bubble = 1 + ((0.0005 * Rsb) * ((sg2 / so)**0.25)) + ((0.0004*(temp2- 60)) / (so * sg2)) # temp in def F

  Bo_array = []

  if pressure2 < P_bubble: # use Vazquez-Beggs
    if api <= 30:
      # use Vazquez-Beggs 
      c1 = 0.0362
      c2 = 1.0937
      c3 = 25.7240
      c4 = 4.677E-4
      c5 = 1.751E-5
      c6 = -1.811E-8
    if api > 30:
      c1 = 0.0178
      c2 = 1.187
      c3 = 23.9310
      c4 = 4.670E-4
      c5 = 1.100E-5
      c6 = 1.337E-9
    Rsc = (pressure2**c2) * c1 * sg2 * np.exp((c3 * api) / (temp2 + 459.67))
    Bo = 1 + (c4 * Rsc) + (c5 * (temp2 - 60) * (api / sg2)) + (c6 * Rsc *(temp2 - 60) * (api / sg2)) # temp in deg F
  if pressure2 == P_bubble:
    # use Levitan-Murtha
    Bo = Bo_bubble
  if pressure2 > P_bubble:
    # Calculate oil compressibility first using Levitan-Murtha
    coil = ((5 * Rsb) + (17.2 * temp2) - (1180 * sg2) + (12.61 * api) - 1433) / (1E+05 * pressure2)
    # Calculate Bo using Levitan-Murtha
    Bo = Bo_bubble * np.exp(coil * (P_bubble - pressure2))
  if P_bubble != P_bubble:
    Bo = np.nan  

  return Bo

In [14]:
Oil_FVF = []
pressure = 1936 # psi
temp = 204 # Fahrenheit
sg = 1.17 # specific gravity
Rsb = 64 # solution gas-oil ratio at bubble-point pressure (scf/STB) (from PVT data)
api = 44 # oil gravity (API)
pbubble = oil_Pb(Rsb, sg, api, temp)
for i in range(len(df)):
    # calculate oil FVF 
    Bo = oil_fvf(pbubble, api, Rsb, sg, temp, df['p'][i])
    Oil_FVF.append(Bo)
df['Oil_FVF'] = Oil_FVF
df

,date,p,Np,Wp,Wi,Gp,Rs,Z_factor,Oil_FVF
0,1996,1950,360085,1845.00,0,23045000,64,0.700638,1.081087
1,1997,1834,17230861,39236.00,0,1102775000,64,0.702142,1.081213
2,1998,1681,38651717,97909.00,0,2473713000,64,0.708127,1.081405
3,1999,1560,68957151,254876.00,0,4413261000,64,0.716362,1.081583
4,2000,1473,95057167,297686.00,38824,6083661000,64,0.724264,1.081730
5,2001,1353,124251053,673783.00,12197536,7952070000,64,0.737850,1.081963
6,2002,1287,154528553,1011278.00,25395003,9889832000,64,0.746588,1.082109
7,2003,1247,191899252,2253789.00,50762076,12281556000,64,0.752293,1.082206
8,2004,1239,229090690,3898144.00,83580287,14661809000,64,0.753470,1.082226
9,2005,1231,265394171,5591112.00,115457824,16985232000,64,0.754658,1.082246
10,2006,1224,301951918,7856842.00,149585083,19324929000,64,0.755707,1.082264
11,2007,1200,338308989,10786529.00,183013606,21651781000,64,0.759368,1.082328
12,2008,1182,373580320,14711414.00,215140193,23909150000,64,0.762179,1.082377
13,2009,1138,405855680,18936798.00,242483501,25974775000,64,0.769273,1.082503
14,2010,1137,439503085,24703101.00,278488838,28128195000,64,0.769438,1.082506
15,2011,1136,456513143,28519165.41,293748836,29219820584,64,0.769603,1.082509

In [15]:
df.to_csv('updated_data.csv')

In [16]:
# alternative way
Bo_test = []
pressure = 1936 # psi
temp = 204 # Fahrenheit
sg = 1.17 # specific gravity
Rsb = 64 # solution gas-oil ratio at bubble-point pressure (scf/STB) (from PVT data)
api = 44 # oil gravity (API)
pbubble = oil_Pb(Rsb, sg, api, temp)

[Bo_test.append(oil_fvf(pbubble, api, Rsb, sg, temp, df['p'][i])) for i in range(len(df))]

df['Bo_test'] = Bo_test
df

,date,p,Np,Wp,Wi,Gp,Rs,Z_factor,Oil_FVF,Bo_test
0,1996,1950,360085,1845.00,0,23045000,64,0.700638,1.081087,1.081087
1,1997,1834,17230861,39236.00,0,1102775000,64,0.702142,1.081213,1.081213
2,1998,1681,38651717,97909.00,0,2473713000,64,0.708127,1.081405,1.081405
3,1999,1560,68957151,254876.00,0,4413261000,64,0.716362,1.081583,1.081583
4,2000,1473,95057167,297686.00,38824,6083661000,64,0.724264,1.081730,1.081730
5,2001,1353,124251053,673783.00,12197536,7952070000,64,0.737850,1.081963,1.081963
6,2002,1287,154528553,1011278.00,25395003,9889832000,64,0.746588,1.082109,1.082109
7,2003,1247,191899252,2253789.00,50762076,12281556000,64,0.752293,1.082206,1.082206
8,2004,1239,229090690,3898144.00,83580287,14661809000,64,0.753470,1.082226,1.082226
9,2005,1231,265394171,5591112.00,115457824,16985232000,64,0.754658,1.082246,1.082246
10,2006,1224,301951918,7856842.00,149585083,19324929000,64,0.755707,1.082264,1.082264
11,2007,1200,338308989,10786529.00,183013606,21651781000,64,0.759368,1.082328,1.082328
12,2008,1182,373580320,14711414.00,215140193,23909150000,64,0.762179,1.082377,1.082377
13,2009,1138,405855680,18936798.00,242483501,25974775000,64,0.769273,1.082503,1.082503
14,2010,1137,439503085,24703101.00,278488838,28128195000,64,0.769438,1.082506,1.082506
15,2011,1136,456513143,28519165.41,293748836,29219820584,64,0.769603,1.082509,1.082509